import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Side_bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const menuItems = [
    { name: "Dashboard", icon: "📊" },
    { name: "Expenses", icon: "💰" },
    { name: "Wallets", icon: "👛" },
    { name: "Summary", icon: "📈" },
    { name: "Accounts", icon: "👤" },
    { name: "Settings", icon: "⚙️" },
  ];

  return (
    <html lang="en" className="dark-mode-default">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Sidebar menuItems={menuItems}>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
